import {
  Activity,
  AlertTriangle,
  Bell,
  Box,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Edit,
  Eye,
  FileText,
  Filter,
  Globe,
  Image,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MoreHorizontal,
  Package,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  Star,
  Tags,
  Trash2,
  Truck,
  User,
  Users,
  X,
  type LucideIcon
} from 'lucide-react';

export const localoIconMap = {
  activity: Activity,
  alert: AlertTriangle,
  audit: FileText,
  bell: Bell,
  box: Box,
  calendar: Calendar,
  categories: Tags,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  commission: ShoppingBag,
  dashboard: LayoutDashboard,
  edit: Edit,
  eye: Eye,
  filter: Filter,
  globe: Globe,
  image: Image,
  location: MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mapPin: MapPin,
  moreHorizontal: MoreHorizontal,
  note: FileText,
  owner: User,
  package: Package,
  phone: Phone,
  plus: Plus,
  products: Package,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  shop: ShoppingBag,
  star: Star,
  support: AlertTriangle,
  trash: Trash2,
  truck: Truck,
  user: User,
  users: Users,
  x: X
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof localoIconMap;
