import {
  Baby,
  Activity,
  AlertTriangle,
  Bell,
  Book,
  Box,
  Calendar,
  Camera,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  Edit,
  Eye,
  FileText,
  Filter,
  Dumbbell,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  LayoutDashboard,
  Laptop,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MoreHorizontal,
  Package,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Scissors,
  Settings,
  Shield,
  Shirt,
  ShoppingBasket,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Store,
  Star,
  Tags,
  Trash2,
  Truck,
  UtensilsCrossed,
  Leaf,
  User,
  Users,
  X,
  type LucideIcon
} from 'lucide-react';

export const localoIconMap = {
  activity: Activity,
  baby: Baby,
  alert: AlertTriangle,
  audit: FileText,
  bell: Bell,
  book: Book,
  box: Box,
  calendar: Calendar,
  camera: Camera,
  categories: Tags,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  coffee: Coffee,
  commission: ShoppingBag,
  car: CarFront,
  dumbbell: Dumbbell,
  dashboard: LayoutDashboard,
  edit: Edit,
  eye: Eye,
  filter: Filter,
  globe: Globe,
  gift: Gift,
  heart: Heart,
  home: Home,
  image: Image,
  location: MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mapPin: MapPin,
  moreHorizontal: MoreHorizontal,
  note: FileText,
  leaf: Leaf,
  laptop: Laptop,
  owner: User,
  package: Package,
  phone: Phone,
  plus: Plus,
  products: Package,
  refresh: RefreshCw,
  search: Search,
  scissors: Scissors,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  shop: ShoppingBag,
  shoppingBasket: ShoppingBasket,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  store: Store,
  star: Star,
  support: AlertTriangle,
  trash: Trash2,
  truck: Truck,
  utensils: UtensilsCrossed,
  user: User,
  users: Users,
  x: X
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof localoIconMap;
